@extends('layouts.policy')
@section('content')
<div class="page">
	<section class="row">
		<div class="spb_content_element col-sm-12 spb_text_column">
			<div class="spb_wrapper clearfix">
				<h1>COOKIES POLICY (WEB)</h1>
			</div>
		</div>
	</section>
	<section class="row">
		<div class="spb_content_element col-sm-12 spb_text_column">
			<div class="spb_wrapper clearfix">
				<h3>a) Use of Cookies in the BabyHelper Website</h3>
				<p>The Babyhelper.info Website (hereinafter the “Website”) uses Cookies and other similar software (hereinafter “Cookies”). Cookies are files sent to a browser from a web server to record a User’s activities in a given website or in all websites. The primary purpose of Cookies is to facilitate faster access to the Services provided by the WEBSITE (hereinafter, the Services). The WEBSITE uses Cookies to personalize and facilitate browsing by a User for each of the functionalities offered. Cookies are associated only with an anonymous User, and they do not provide any references which might allow deduction of the User’s personal details. Users can configure their browsers to report and block the installation of Cookies sent by the WEBSITE. However, disabling Cookies in your browser can limit the functionalities and Services provided by the BabyHelper, and it may affect the quality of the WEBSITE’s functioning.</p>
			</div>
		</div>
	</section>
	<section class="row">
		<div class="spb_content_element col-sm-12 spb_text_column">
			<div class="spb_wrapper clearfix">
				<h3>b) Types, purpose and functioning of Cookies</h3>
				<p>Depending <strong>who manages the device or domain from which Cookies are sent</strong>, we may distinguish between own Cookies (managed by BabyHelper, S.A.) and third-party Cookies (managed by third-party entities processing the data obtained).</p>
				<p><strong>OWN COOKIES</strong></p>
				<ul>
				<li><strong>Personalization Cookies:</strong> These Cookies remember your preferences for the tools provided in the Services, so that you do not have to reconfigure the service each time you visit the WEBSITE. These are session cookies, which means they are utilized while a session is in progress in any of the applications, or they are used for a specific functionality. The functions of this kid of cookies include identification of the browser language to show WEB content in the right language.</li>
				</ul>
				<p>Furthermore, some of the WEB Services use links to social networks like Facebook, Twitter and others (share buttons on our website, and follow BabyHelper buttons on social networks).</p>
				<p><strong>THIRD-PARTY COOKIES</strong></p>
				<ul>
					<li><strong>Analytic cookies:</strong> We use these cookies to count the number of users and to carry out statistical measurements and analyses of the use made of the WEBSITE. We analyse the use of the WEBSITE to enhance and/or improve the range of products and services offered. These cookies are generated by Google.</li>
				</ul>
				<p>Each time a User visits a Service, a tool belonging to an external provider (Google) generates analytic Cookies in the User’s device. These Cookies are generated only when the User takes any action. They are permanent and they are used to identify the visitor anonymously in future visits to the WEB Services. Users should note that permanent cookies expire when they have served their purpose or when they are manually deleted.</p>
				<p>The analytic Cookies utilized in the WEBSITE are:</p>
				<table>
					<thead>
						<tr>
							<th>Type</th>
							<th>Name</th>
							<th>Description</th>
							<th>Purpose</th>
							<th>Other Information</th>
						</tr>
					</thead>
					<tbody>
						<tr>
							<td rowspan="3"><strong>Analytic cookies (Google Analytics)</strong></td>
							<td><strong>__utma</strong></td>
							<td>
								Used to distinguish users and sessions. The cookie is created when the JavaScript library is executed and there is no __utma cookie installed. The cookie is updated each time data are sent to Google Analytics.
							</td>
							<td rowspan="3">
								<p>To identify Users anonymously via the Cookie (which identifies browsers and devices, not persons) and therefore to generate an approximate tally of the number of visitors and keep track of trends over time.</p>
								<p>To identify the most visited and attractive content for Users anonymously.</p>
								<p>To learn whether a User is new or is making a repeat visit.</p>
							</td>
							<td rowspan="3">
								<a href="https://developers.google.com/analytics/devguides/collection/analyticsjs/cookie-usage?hl=es" target="_blank">Google Site</a>
							</td>
						</tr>
						<tr>
							<td>
								<strong>__utmz</strong>
							</td>
							<td>
								This cookie stores the source of traffic or campaign explaining how the user reached the site. The cookie is created when the JavaScript library is executed, and it is updated each time data are sent to Google Analytics.
							</td>
						</tr>
						<tr>
							<td><strong>__ga</strong></td>
							<td>
								Used to distinguish Users.
							</td>
						</tr>
					</tbody>
				</table>
				<br/><br/>
				<p>These cookies can be deleted. In such case, WEBSITE will continue with optimum functioning but the Services will be affected.</p>
				<p>Further information on the Google Analytics privacy policy will be found on <a href="http://www.google.com/intl/en/policies/" target="_blank">http://www.google.com/intl/en/policies/</a>.</p>
			</div>
		</div>
	</section>
	<section class="row">
		<div class="spb_content_element col-sm-12 spb_text_column">
			<div class="spb_wrapper clearfix">
				<h3>c) How to disable Cookies in browsers<strong><br>
				</strong></h3>
				<p>Users can choose what cookies they wish to allow at any time by accessing their browser’s setup panel:</p>
				<ul>
				<li><strong>Internet Explorer:</strong> Tools -&gt; Internet Options -&gt; Privacy -&gt; Configuration</li>
				</ul>
				<p>For further information, consult <a href="http://windows.microsoft.com/en-us/windows/support#1TC=windows-10" target="_blank">Microsoft support</a> or the browser Help function.</p>
				<ul>
				<li><strong>Firefox:</strong> Tools -&gt; Options -&gt; Privacy -&gt; History -&gt; Personalized Configuration</li>
				</ul>
				<p>For further information, consult <a href="https://support.mozilla.org/en-US/" target="_blank">Mozilla support</a> or the browser Help function.</p>
				<ul>
				<li><strong>Chrome:</strong> Configuration -&gt; Show advanced options -&gt; Privacy -&gt; Content configuration</li>
				</ul>
				<p>For further information, consult <a href="https://support.google.com/?hl=en" target="_blank">Google support</a> or the browser Help function.</p>
				<ul>
				<li><strong>Safari:</strong> Preferences -&gt; Security</li>
				</ul>
				<p>For further information, consult <a href="http://www.apple.com/support/mac-apps/safari/" target="_blank">Apple support</a> or the browser Help function.</p>
				<p>To disable the analytic cookies generated by Google Analytics for browsers, visit the following link: <a href="https://support.google.com/analytics/answer/181881?hl=en" target="_blank">https://support.google.com/analytics/answer/181881?hl=en </a></p>
			</div>
		</div>
	</section>
	<section class="row">
		<div class="spb_content_element col-sm-12 spb_text_column">
			<div class="spb_wrapper clearfix">
				<h3>d) What happens if Cookies are disabled?<strong><br>
				</strong></h3>
				<p>Certain functionalities of the Services will be disabled, such as browser language detection, personalized video viewing and explicit acceptance of the cookies policy.</p>
				<p><strong>UPDATES AND CHANGE IN COOKIES POLICY</strong></p>
				<p>BabyHelper may amend this Cookies Policy based on changes in the Cookies utilized from time to time, in view of changes in legislative and regulatory requirements, and in order to bring the policy into line with instructions issued by the Spanish Data Protection Agency. Accordingly, Users are advised to visit the Cookies policy periodically.</p>
				<p>If any significant changes are made to this Cookies Policy, Users will be notified for the purposes of acceptance on the WEBSITE, by e-mail or by any other appropriate means in the circumstances.</p>
				<p>If you have any questions about this Cookies Policy, please <a href="/contact">write us</a>.</p>
				<p style="text-align: right;"><em>(Last revision 23th May 2018)</em></p>
			</div>
		</div>
	</section>
</div>
@endsection
